### PR TITLE
autocomplete_light compatibility

### PR DESCRIPTION
**Pull request by ikcam**
This small change allow to submit the forms. This issue was summited on the autocomplete_light repo but is not their issue.

https://github.com/yourlabs/django-autocomplete-light/issues/498

### CODE REVIEW

**Comment by adriaant** [comment]
What does "autocomplete" have to do with the "required" flag on a form field?

**Comment by ikcam** [comment]
The problem is that as soon as you make enough selections, the <input type=text name="id_yourfield-autocomplete" ...> is hidden, even though it has an empty value and required="required" set. So what happens when you submit the form is that the browser tries to do form validation but can't show the Please fill out this field error messages because the element is hidden.

**Comment by dyve** [comment]
If a JavaScript plugin intentionally hides a required input, it should also remove the required attribute.

**Comment by dyve** [comment]
Elaborating on my previous response. If the Django backend says the input is required, the input will be marked as required (unless `django-bootstrap3` is otherwise configured. We cannot accommodate for the DOM changes JavaScript plugins apply. For example, a plugin that has nothing to do with `autocomplete-light` might apply the `autocomplete` attribute, and not expect `required` to be "skipped" because of that.

So this pull request will not be merged into `django-bootstrap3`.

**Pull request closed without merging**
