### PR TITLE
Add: Feature request #380

### PR DESCRIPTION
**Pull request by ikcam**
Add `errors_type` support in the `{% bootstrap_form %}` tag.

### CODE REVIEW

**Comment by dvl** [comment]
Is there any chance of this getting merged?

**Comment by Wolfizen** [comment]
This would be nice to get merged! I'm currently using a custom form renderer to fix this locally but having it merged into upstream would be great.

**Comment by puttu** [comment]
I believe for most use cases the expected behavior is that only non-field errors are rendered above the form. Perhaps it would be a good idea to change the `errors_type` default setting from `all` to `non_fields`?

**Comment by ikcam** [comment]
Featured added in #406.

**Pull request closed without merging**
