### PR TITLE
field_class and label_class copied from widget attrs if not yet set (…

### PR DESCRIPTION
**Pull request by biggosh**
Hi.

my solution for #428 

Hope this can be accepted.
I haven't checked: but for me this solution (if there isn't anyone else) can be applied to others attributes.

Thanks
BG

### CODE REVIEW

**Comment by dyve** [comment]
See discussion at #428

**Comment by biggosh** [comment]
You closed the discussion without giving a solution to my problem. In #428 you write something about css class ...

**Comment by dyve** [comment]
The `attrs` kwarg is in this Django code to add a HTML attribute. A CSS class is not a HTML attribute. That's why this PR was refused and closed. I'll see if I can help with a solution to the problem over on #428.

**Comment by biggosh** [comment]
Thank you.

**Pull request closed without merging**
