### PR TITLE
Support Django 1.9 and Python 3.5

### PR DESCRIPTION
**Pull request by jonashaag**

### CODE REVIEW

**Comment by adriaant** [comment]
`from django.forms import BaseForm, BoundField` does not work on Django < 1.9. You'll need a try/catch wrapper.

**Comment by jieter** [comment]
Wasn't looking at the existing PRs when I made mine, that's how I did it: #278

**Comment by jonashaag** [comment]
@jieter can you merge our changes so I can close this PR?

**Comment by jonashaag** [comment]
Import works with latest version of Django 1.9

**Pull request merged**
