### PR TITLE
CSS classes arguments passed to the bootstrap_form are now working

### LINKED ISSUE #275: required_css_class argument in {% bootstrap_form form ... %}
Hi!

I'm trying to set required_css_class for a specific form rendering without using it like a global setting in BOOTSTRAP3.
So, when I read http://django-bootstrap3.readthedocs.org/en/latest/templatetags.html#bootstrap-form ("See bootstrap_field for other arguments") I understood that by doing this:
`{% bootstrap_form myform required_css_class='required' %}`
I get what I wanted... but it didn't work... :(

Is there a problem in bootstrap_form template tags? or am I doing something wrong?

I'm using django-bootstrap3 6.2.2

Thank you very much in advance for any help

### PR DESCRIPTION
**Pull request by gordon-**
This PR fixes #275

### CODE REVIEW

**Comment by dyve** [comment]
I'm out of the country for a few days, so I won't be able to check this out immediately

**Comment by dyve** [comment]
Also there is a Python 3.2 test failing, if you could see if you could submit a PR that passes all tests, that would help.

**Comment by gordon-** [comment]
As I can see, the tests are failing because of a syntax error on coverage package, and I cannot see if it’s my fault. The error message mentions a "u' '" syntax in "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/annotate.py", and I’m not using this syntax

**Comment by gordon-** [comment]
Apparently, the source of the problem is really Coveralls: their build is failing too, and it seems that it’s an expected failure in 3.2: https://travis-ci.org/coagulant/coveralls-python/jobs/75434967

**Comment by dyve** [comment]
I fixed the Travis CI settings and pulled this in, tests should work now

**Pull request merged**
