### PR TITLE
Add FA icons template tag

### PR DESCRIPTION
**Pull request by sshaman1101**
I'd prefer to add template tag for easy including [Font Awesome](http://fortawesome.github.io/Font-Awesome/icons/) icons into templates.

(sorry if I made something wrong, is my first pull request)

### CODE REVIEW

**Comment by dyve** [comment]
I like the idea, but if we go in this direction we'd get bootstrap_XXX_icon for various classes. Give me some time to think how to handle multiple icon libraries (input welcome)

**Comment by sshaman1101** [comment]
I have not thought about such a situation, it may be worthwhile to introduce a set of options to specify the type of icons, but uses Font Awesome tag <i>, Glyphicons uses the tag <span>. This will cause quite a big change.

(it requires a factory method, if I understand something in programming?)

**Comment by dyve** [comment]
Well, maybe your solution will be fine. I have never used Font Awesome myself (may start, it looks very pretty). Also, a ```bootstrap_fa``` tag might be more appropriate than a ```bootstrap_icon_fa``` tag. 

Thanks for submitting this!

**Comment by sshaman1101** [comment]
Thanks for reply, it was my first pull request, it not so hard as I imagined at first :)

Will fix tag naming.

**Comment by dyve** [comment]
Since Font Awesome uses the ```fa``` and ```fa-*``` classes, a ```bootstrap_fa``` template tag seems the way to go.

I'd welcome comments from other followers and contributors.

**Comment by dyve** [comment]
The only other thing I can think of is to make a separate app for Font Awesome. Since it is not dependent on Bootstrap, that might be the best thing to do. I really like FA now that I have seen it.

**Comment by dyve** [comment]
I have started `django-fa`. Font Awesome is not the same as bootstrap, and should be it's own app.
https://github.com/zostera/django-fa

**Comment by dyve** [comment]
@sshaman1101:
- Thanks for bringing this up!
- Sorry that this cannot be part of django-bootstrap3
- You are welcome to add any pull requests to the `django-fa` app.

**Pull request closed without merging**
