### PR TITLE
Add basic tag that generates tabs

### PR DESCRIPTION
**Pull request by melvyn-sopacua**
Will be filling branch with more commits as I implement them.

Goals:
- extra css classes for li elements
- pills variant
- bootstrap_tabs_activate for corresponding js snippet
- docs (*whistle*)
- maybe: bootstrap_tabs_container block tag for the actual tab content

### CODE REVIEW

**Comment by melvyn-sopacua** [comment]
Ready for feedback.

**Comment by auvipy** [comment]
was wondering why this isn't merged yet

**Comment by dyve** [comment]
Thanks very much for the contribution. It's quite a big addition, and some of the parameter names do not match the rest on the package. I'm not sure we can pull this is as is. Will look at it when I have time.

**Comment by dyve** [comment]
I'm going to close this, it doesn't quite fit the rest of the package. Thanks again for taking the time to contribute.

**Pull request closed without merging**
