### PR TITLE
Test Python 3.5 and Django 1.9 on Travis

### PR DESCRIPTION
**Pull request by jonashaag**
This has accidentally been removed in 1feaacc3f20d085138af82edab50387709bed65d

### CODE REVIEW

**Comment by nikolas** [comment]
:+1:

**Comment by nikolas** [comment]
We should exclude testing on python 3.2 and 3.3 with django 1.9, since django 1.9 doesn't support those python versions.

**Comment by dyve** [comment]
For now, CI related pull requests should have passing Travis tests, so I am not pulling this in.

**Comment by jonashaag** [comment]
#294

**Pull request closed without merging**
