### PR TITLE
Handle MultiWidget properly

### LINKED ISSUE #248: Missing sub widgets classes in django.contrib.admin.widgets.AdminSplitDateTime widget rendering
adminAdminSplitDateTime is a MultiWidget consisting of an AdminDateWidget and a AdminTimeWidget. When rendered with django-bootstrap3 both are missing respectively a vDateField and vTimeField class so the django default javascript does not work.

Sort of a test case:
```
from django.contrib.admin.widgets import AdminSplitDateTime

class RendererTestCase(TestCase):
        def setUp(self):
            class TestForm(forms.Form):
                datetime = forms.DateTimeField(widget=AdminSplitDateTime())

            self.form = TestForm({
                'datetime': '20140111 10:00:00',
            })

        def test_render_datetime(self):
            field = self.form['datetime']
            html = renderers.FieldRender(field).render()
            #html = field.as_widget()
            self.assertIn('vDateField', html)
            self.assertIn('vTimeField', html)
```

### PR DESCRIPTION
**Pull request by xrmx**
Instead of poking with the MultiWidget poke with the sub widgets.
This fixes django.contrib.admin.widgets.AdminSplitDateTime rendering.
Fixes #248

### CODE REVIEW

**Comment by jleszczynski** [comment]
Hello, tried the pull request and I'm getting:
Exception Value:	
add_class_attrs() takes exactly 1 argument (2 given)
bootstrap3/renderers.py in add_widget_attrs, line 303

**Comment by xrmx** [comment]
@jleszczynski the patch changes some renderers.FieldRenderer's method signatures so it's breaking apps that subclass it.

**Comment by andreip** [comment]
@xrmx I wanted to do the same thing, apply functions for each widget, but found your PR ; for me it works fine after I merged your patch this in current master.

**Comment by dyve** [comment]
I pulled this in, changed the name of a var (multi_widget to is_multi_widget) and fixed the merge conflicts. Thanks! Please confirm ``develop`` works as intended for you.

**Comment by andreip** [comment]
I can confirm both develop and master 6.2.0 render properly now. Thanks!

**Pull request merged**
